name: ice_code_editor
version: 0.0.1
description: Code Editor + Preview
author: Chris Strom <chris@eeecomputes.com>
homepage: https://github.com/eee-c/ice-code-editor
dependencies:
  unittest: 0.4.0
  js: any
