name: ice_code_editor
version: 0.1.0
description: Code Editor + Preview
authors:
- Chris Strom <chris@eeecomputes.com>
- Santiago Arias <santiago.ariassar@gmail.com>
- Srdjan Pejic <spejic@gmail.com>
homepage: https://github.com/eee-c/ice-code-editor
dependencies:
  crypto: ">=0.9.0 < 0.10.0"
  js: ">=0.2.0 <0.2.1"
  ctrl_alt_foo: ">=0.3.0 <0.3.1"
dev_dependencies:
  unittest: any
