name: ice_code_editor
version: 0.0.3
description: Code Editor + Preview
authors:
- Chris Strom <chris@eeecomputes.com>
- Santiago Arias <santiago.ariassar@gmail.com>
- Srdjan Pejic
homepage: https://github.com/eee-c/ice-code-editor
dependencies:
  unittest: ">=0.5.20 <0.5.21"
  js: ">=0.0.22 <0.0.23"
  crypto: ">=0.5.20 <0.5.21"
